name: Open Pull Request to merge changes to kusama-nft

on:
  push:
    branches:
      - polkadot-nft

jobs:
  open-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout polkadot-nft
        uses: actions/checkout@v3
        with:
          ref: kusama-nft
      - name: Reset promotion branch
        run: |
          git fetch origin polkadot-nft:polkadot-nft
          git reset --hard polkadot-nft
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          title: 'Merge polkadot-nft to kusama-nft'
          body: 'This pull request merges the polkadot-nft branch to the kusama-nft branch.'
          branch: kusama-nft-sync
